// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY0bslR947EUqQn0TN6aDjr7kM0H9ddrw',
    appId: '1:951060218171:android:9adcd06a512e95b844b71e',
    messagingSenderId: '951060218171',
    projectId: 'angafit-f7d6e',
    storageBucket: 'angafit-f7d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12-XVUbgTkd0CDZ6aVj4CYB3jVnZYPPA',
    appId: '1:951060218171:ios:6886998e2f52c38c44b71e',
    messagingSenderId: '951060218171',
    projectId: 'angafit-f7d6e',
    storageBucket: 'angafit-f7d6e.firebasestorage.app',
    iosBundleId: 'com.example.AngaFit',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCWjx5eOlWZ19bH5jlJGr0H2f0FSpMLI',
    appId: '1:951060218171:web:7fbe87b41ef00c9a44b71e',
    messagingSenderId: '951060218171',
    projectId: 'angafit-f7d6e',
    authDomain: 'angafit-f7d6e.firebaseapp.com',
    storageBucket: 'angafit-f7d6e.firebasestorage.app',
    measurementId: 'G-THCKME0NXK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12-XVUbgTkd0CDZ6aVj4CYB3jVnZYPPA',
    appId: '1:951060218171:ios:38dc8aa6065c0c8e44b71e',
    messagingSenderId: '951060218171',
    projectId: 'angafit-f7d6e',
    storageBucket: 'angafit-f7d6e.firebasestorage.app',
    iosBundleId: 'com.example.angafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfCWjx5eOlWZ19bH5jlJGr0H2f0FSpMLI',
    appId: '1:951060218171:web:e3aee135ae7b16fe44b71e',
    messagingSenderId: '951060218171',
    projectId: 'angafit-f7d6e',
    authDomain: 'angafit-f7d6e.firebaseapp.com',
    storageBucket: 'angafit-f7d6e.firebasestorage.app',
    measurementId: 'G-6Q9RN4LMDG',
  );

}