import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'core/theme/app_theme.dart';
import 'features/splash/splash_screen.dart';

void main() async {
  // 1. Ensure Flutter framework is fully initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with platform-specific options
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase Initialization Error: $e");
  }

  runApp(const AngaFit());
}

class AngaFit extends StatelessWidget {
  const AngaFit({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'AngaFit',
      // Using the centralized theme we created
      theme: AppTheme.lightTheme,
      // Starting the app with the Splash Screen
      home: const SplashScreen(),
    );
  }
}
